### PR TITLE
update/added timezone to allow programmatic access

### PR DESCRIPTION
**Pull request by devgenix**

### CODE REVIEW

**Review by aybruhm — COMMENTED** [review]
There's already a field that handles the date and time the API key would expired. It's called `expiry_date`.

**Comment by devgenix** [comment]
> There's already a field that handles the date and time the API key would expired. It's called `expiry_date`.

Yeah I saw it, I added the timezone to it because I was getting this error when creating the Client API in the Server SSH Terminal: "RuntimeWarning: DateTimeField APIKey.expiry_date received a naive datetime (2023-08-25 09:47:50.297940) while time zone support is active."

Screenshot 2023-05-18 at 11 12 23

**Comment by devgenix** [comment]
> `expiry_date`

Where is this field?

**Comment by aybruhm** [comment]
> > There's already a field that handles the date and time the API key would expired. It's called `expiry_date`.
> 
> Yeah I saw it, I added the timezone to it because I was getting this error when creating the Client API in the Server SSH Terminal: "RuntimeWarning: DateTimeField APIKey.expiry_date received a naive datetime (2023-08-25 09:47:50.297940) while time zone support is active."
> 
> Screenshot 2023-05-18 at 11 12 23

You should have ignored that!

**Comment by aybruhm** [comment]
> > `expiry_date`
> 
> Where is this field?

It's coming from the APIKey class that ClientAPIKey is inheriting.

**Pull request merged**
