### PR TITLE
Chore/enhancements

### LINKED ISSUE #1: Create interactive docs
The state of the docs is currently nothing to write home about. 

Please, create a more descriptive and interactive doc, preferably using drf-yasg or any other options of your choice.

### LINKED ISSUE #2: rewrite function based views to class based views.
The business logic is currently written as function-based views to result in fat views unnecessarily handling validation. 

This is a total code rewriting process to use class-based views to result in thin view and fat serializers with the serializer handling validations.

### PR DESCRIPTION
**Pull request by aybruhm**
The following has been worked on:

- enhanced every function-based views to class-based views
- added docstrings to models
- installed drf-yasg for API documentation
- created selectors module
- configure security definition for swagger doc authentication

Merging this PR will close #1 and #2

### CODE REVIEW

**Review by devgenix — COMMENTED** [review]
@aybruhm what's the essence of replacing ' with " ?

**Comment by aybruhm** [comment]
> @aybruhm what's the essence of replacing ' with " ?

Oh, that. I am using black to format my code. Black just prefers double quotes to single ones, see [here](https://github.com/psf/black/issues/118).

**Review by devgenix — APPROVED** [review]
Omo is the only thing that escaped my mouth. I reviewed every line of code and bruh you frigging deleted like 50 lines of my code. ( crying emoji )

**Comment by devgenix** [comment]
> > @aybruhm what's the essence of replacing ' with " ?
> 
> Oh, that. I am using black to format my code. Black just prefers double quotes to single ones, see [here](https://github.com/psf/black/issues/118).

Black what now?

**Comment by aybruhm** [comment]
> > > @aybruhm what's the essence of replacing ' with " ?
> > 
> > 
> > Oh, that. I am using black to format my code. Black just prefers double quotes to single ones, see [here](https://github.com/psf/black/issues/118).
> 
> Black what now?

Black [documentation](https://black.readthedocs.io/en/stable/index.html).

**Comment by devgenix** [comment]
> 

Thankfully you read it that way.

**Pull request merged**
