### PR TITLE
Feat: Rate Limiting by API Key

### LINKED ISSUE #8: Add rate limiting by API keys to 50 requests/hour

### PR DESCRIPTION
**Pull request by aybruhm**
I did the following;

- created a custom throttling class to limit API requests by API key
- configured throttle class to rest_framework and added throttle_scope on all API views

Below is a demo of how the throttling feature works:

[238192212-b761b86d-bb53-4910-b050-1c697dcd4246.webm](https://github.com/faradayafrica/Univast/assets/55067204/03102951-2171-45bc-a97f-09b04fc14b32)

This PR resolves #8

### CODE REVIEW

**Comment by devgenix** [comment]
> I did the following;
> 
>     * created a custom throttling class to limit API requests by API key
> 
>     * configured throttle class to rest_framework and added throttle_scope on all API views
> 
> 
> The following below is a demo of how the throttling feature works:
> univast-throttling-demo.mp4
> 
> This PR resolves #8

this is absolutely beautiful.

**Comment by devgenix** [comment]
> I did the following;
> 
>     * created a custom throttling class to limit API requests by API key
> 
>     * configured throttle class to rest_framework and added throttle_scope on all API views
> 
> 
> The following below is a demo of how the throttling feature works:
> univast-throttling-demo.mp4
> 
> This PR resolves #8

In trying to play the video, I get an error "Video can't be played because the file is corrupt"

**Comment by aybruhm** [comment]
> > I did the following;
> > ```
> > * created a custom throttling class to limit API requests by API key
> > 
> > * configured throttle class to rest_framework and added throttle_scope on all API views
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The below is a demo of how the throttling feature works:
> > univast-throttling-demo.mp4
> > This PR resolves #8
> 
> In trying to play the video, I get an error "Video can't be played because the file is corrupt"

[238192212-b761b86d-bb53-4910-b050-1c697dcd4246.webm](https://github.com/faradayafrica/Univast/assets/55067204/87c62b2c-e5cb-4129-af61-45b2f89b218e)


Try again. If the error persists, try accessing the PR link from an incognito window.

**Review by devgenix — COMMENTED** [review]
Can rates be managed in Django Admin such that it can be reduced or increased per API Key?

**Comment by devgenix** [comment]
> 

It still doesn't work in an incognito window. 
Try uploading it to Loom or Vimeo or unlisted on Youtube.

**Comment by aybruhm** [comment]
> Can rates be managed in Django Admin such that it can be reduced or increased per API Key?

Yes, it can.

**Comment by aybruhm** [comment]
> > 
> 
> It still doesn't work in an incognito window. 
> Try uploading it to Loom or Vimeo or unlisted on Youtube. 

Mm. Very well, then. I shall do that later today when light comes up.

**Comment by devgenix** [comment]
> > Can rates be managed in Django Admin such that it can be reduced or increased per API Key?
> 
> Yes, it can.

Okay, let's do that.

**Comment by devgenix** [comment]
> > > 
> > 
> > 
> > It still doesn't work in an incognito window.
> > Try uploading it to Loom or Vimeo or unlisted on Youtube.
> 
> Mm. Very well, then. I shall do that later today when light comes up.

Alternatively, you can send it to me on the workspace.

**Review by devgenix — APPROVED** [review]
All good man. I've tested it and it works.

**Pull request merged**
